import = [
    "~/.config/alacritty/themes/alabaster.toml",
    "/tmp/theme.toml",
]

[window]
resize_increments = true
dynamic_padding = true

[font]
normal = { family = "JetBrainsMonoNL Nerd Font" }
size = 8

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
{ key = "Escape", mode = "Vi", action = "ToggleViMode" },
]
