# To symlink to ~/.cargo/config.toml

[alias]
b = "build"
c = "clippy"
t = "test"
nt = "nextest run"

r = "run"
rr = "run --release"
ex = "run --example"

i = "install"
un = "uninstall"
rm = "remove"
