promptToReturnFromSubprocess: false
gui:
  nerdFontsVersion: "3"
notARepository: 'quit'
customCommands:
  - key: 'F'
    context: 'global'
    command: 'git fetch --prune --prune-tags'
    description: 'fetch and prune unused items'
    loadingText: 'fetching & pruning'
