promptToReturnFromSubprocess: false

gui:
  nerdFontsVersion: "3"
  expandFocusedSidePanel: true

notARepository: 'quit'

customCommands:
  - key: 'F'
    context: 'global,localBranches,commits'
    command: 'git fetch --prune --prune-tags'
    description: 'fetch and prune unused items'
    loadingText: 'fetching & pruning'
